orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1

jobs:
  yarnJob:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - run: echo "this is the yarn job"
      - run: yarn
  buildJob:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - run: echo "this is the build job"
      - run: yarn build

workflows:
  yarn-and-build:
    jobs:
      - yarnJob
      - buildJob:
          requires:
            - yarnJob